name: build with openssl 3.0 in docker

on:
  push:
    branches:
     - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout project
      uses: actions/checkout@v3

    - name: compile nginx-proxy
      uses: aericpp/building-docker
      env:
        script_file: compile.sh
        depend_list: build-essential libpcre3-dev zlib1g-dev

    - name: Upload artifact
      if: |
        ${{
          steps.check_release.outputs.FLAG == 1 ||
            github.event_name == 'push'
        }}
      uses: actions/upload-artifact@master
      with:
        name: nginx
        path: |
          nginx_proxy.deb
          nginx_proxy_deb_src.tar.gz
