name: ci-docker

on:
  push:
    branches:
     - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: compile nginx-proxy
      uses: aericpp/building-docker@main
      with:
        script_file: compile.sh
        depend_list: build-essential libpcre3-dev zlib1g-dev git

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: nginx
        path: |
          nginx_proxy.deb
          nginx_proxy_deb_src.tar.gz
