name: ci-docker

on:
  push:
    branches:
     - 'main'  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout project
      uses: actions/checkout@v3

    - name: compile nginx-proxy
      uses: aericpp/building-docker@main
      with:
        script_file: compile.sh
        depend_list: build-essential libpcre3-dev zlib1g-dev git

    - name: check release
      id: check_release
      run: |
        cat tmp.flag
        cat release.version
        echo "FLAG=$(cat tmp.flag)" >> $GITHUB_OUTPUT
        echo "TAG_NAME=$(cat release.version)" >> $GITHUB_OUTPUT

    - name: upload artifact
      if: ${{ steps.check_release.outputs.FLAG == 1 }}
      uses: actions/upload-artifact@master
      with:
        name: nginx
        path: |
          nginx_proxy.deb
          nginx_proxy_deb_src.tar.gz

    - name: release
      if: ${{ steps.check_release.outputs.FLAG == 1 }}
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ format('nginx_{0}', steps.check_release.outputs.TAG_NAME) }}
        tag: ${{ format('{0}', steps.check_release.outputs.TAG_NAME) }}
        artifacts: 'nginx_proxy.deb, nginx_proxy_deb_src.tar.gz'