name: build with openssl 3.0

on:
  push:
    branches:
     - 'main'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '12 2 * * 2'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Clone nginx
      id: check_nginx
      run: |
        git clone https://github.com/nginx/nginx.git
        cd nginx
        test -f .hgtags && cat .hgtags |tail -n 1 |awk '{print $2}'
        VER=$(test -f .hgtags && cat .hgtags |tail -n 1 |awk '{print $2}')
        git checkout $VER
        echo "::set-output name=VER::$(echo $VER)"
        echo "[DEBUG] steps.check_nginx.outputs.VER" $VER
        current=$(date +%s)
        last=$(git log --pretty=format:"%at" $(git rev-parse HEAD) -1)
        min=`expr $current - $last`
        echo "::set-output name=UPDATE::$(echo 1)"
        if [ $min -gt 86400 ];then
          echo "::set-output name=UPDATE::$(echo 0)"
          echo "[DEBUG] steps.check_nginx.outputs.UPDATE 0"
        fi

    - name: Clone Openssl
      id: check_openssl
      run: |
        git clone https://github.com/openssl/openssl.git
        cd openssl
        git log --simplify-by-decoration --pretty="format:%ct %D" --tags \
          | grep openssl-3. \
          | sort -n -k 1 -t " " -r \
          | head -n 1 \
          | awk '{print $3}'
        VER=$(git log --simplify-by-decoration --pretty="format:%ct %D" --tags \
          | grep openssl-3. \
          | sort -n -k 1 -t " " -r \
          | head -n 1 \
          | awk '{print $3}')
        git checkout $VER
        echo "::set-output name=VER::$(echo $VER)"
        echo "[DEBUG] steps.check_openssl.outputs.VER" $VER
        current=$(date +%s)
        last=$(git log --pretty=format:"%at" $(git rev-parse HEAD) -1)
        min=`expr $current - $last`
        echo "::set-output name=UPDATE::$(echo 1)"
        if [ $min -gt 86400 ];then
          echo "::set-output name=UPDATE::$(echo 0)"
          echo "[DEBUG] steps.check_openssl.outputs.UPDATE 0"
        fi

    - name: Clone ngx_http_proxy_connect_module
      run: |
        git clone https://github.com/chobits/ngx_http_proxy_connect_module.git        
        echo "[DEBUG] steps.check_nginx.outputs.UPDATE" ${{ steps.check_nginx.outputs.UPDATE }}
        echo "[DEBUG] steps.check_nginx.outputs.VER" ${{ steps.check_nginx.outputs.VER }}
        echo "[DEBUG] steps.check_openssl.outputs.UPDATE" ${{ steps.check_openssl.outputs.UPDATE }}
        echo "[DEBUG] steps.check_openssl.outputs.VER" ${{ steps.check_openssl.outputs.VER }}
        echo "[DEBUG] env.GITHUB_EVENT_NAME" ${{ github.GITHUB_EVENT_NAME }}

    - name: For test outputs
      if: ${{ steps.check_openssl.outputs.UPDATE == 1 || steps.check_nginx.outputs.UPDATE == 1 }}
      run: |
        echo "test"

    - name: For test Event
      if: ${{ steps.check_openssl.outputs.UPDATE == 1 || steps.check_nginx.outputs.UPDATE == 1 || github.GITHUB_EVENT_NAME == 'push' }}
      run: |
        echo "test"
