name: build with openssl 3.0

on:
  push:
    branches:
     - 'main'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '12 2 * * 2'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
      
    - name: Clone Openssl
      id: check_openssl
      run: |
        git clone https://github.com/openssl/openssl.git
        cd openssl
        git tag --sort=-committerdate -l 'openssl-3.*'
        VER=$(git tag --sort=-committerdate -l 'openssl-3.*' | head -n 1)
        git checkout $VER
        echo "::set-output name=VER::$(echo $VER)"
        echo "[DEBUG] steps.check_openssl.outputs.VER" $VER
        current=$(date +%s)
        last=$(git log --pretty=format:"%at" $(git rev-parse HEAD) -1)
        min=`expr $current - $last`
        echo "::set-output name=UPDATE::$(echo 1)"
        if [ $min -gt 86400 ];then
          echo "::set-output name=UPDATE::$(echo 0)"
          echo "[DEBUG] steps.check_openssl.outputs.UPDATE 0"
        fi

    - name: Clone nginx
      id: check_nginx
      run: |
        git clone https://github.com/nginx/nginx.git
        cd nginx
        git tag --sort=-committerdate -l 'release-*' | head -n 1
        VER=$(git tag --sort=-committerdate -l 'release-*' | head -n 1)
        git checkout $VER
        echo "::set-output name=VER::$(echo $VER)"
        echo "[DEBUG] steps.check_nginx.outputs.VER" $VER
        current=$(date +%s)
        last=$(git log --pretty=format:"%at" $(git rev-parse HEAD) -1)
        min=`expr $current - $last`
        echo "::set-output name=UPDATE::$(echo 1)"
        if [ $min -gt 86400 ];then
          echo "::set-output name=UPDATE::$(echo 0)"
          echo "[DEBUG] steps.check_nginx.outputs.UPDATE 0"
        fi

    - name: Clone ngx_http_proxy_connect_module
      run: |
        git clone https://github.com/chobits/ngx_http_proxy_connect_module.git        
        echo "[DEBUG] steps.check_nginx.outputs.UPDATE" ${{ steps.check_nginx.outputs.UPDATE }}
        echo "[DEBUG] steps.check_nginx.outputs.VER" ${{ steps.check_nginx.outputs.VER }}
        echo "[DEBUG] steps.check_openssl.outputs.UPDATE" ${{ steps.check_openssl.outputs.UPDATE }}
        echo "[DEBUG] steps.check_openssl.outputs.VER" ${{ steps.check_openssl.outputs.VER }}

    - name: Compile nginx
      if: ${{ steps.check_openssl.outputs.UPDATE || steps.check_nginx.outputs.UPDATE }}
      run: |
        echo "test"
