name: build nginx

on:
  push:
    branches:
    - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '12 2 * * 2'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
      
    - name: Clone Openssl
      id: check_openssl
      run: |
        git clone https://github.com/openssl/openssl.git
        cd openssl
        VER=$(git tag --sort=taggerdate -l 'openssl-3.*' | tail -n 1)
        git checkout $VER
        echo "::set-output name=OPENSSL::$VER"
        echo "[DEBUG] steps.check_openssl.outputs.OPENSSL" $VER
        current=$(date +%s)
        last=$(git log --pretty=format:"%at" $(git rev-parse HEAD) -1)
        min=`expr $current - $last`
        echo "::set-output name=UPDATE::1"
        if [ $min -gt 86400 ];then
          echo "::set-output name=UPDATE::0"
          echo "[DEBUG] steps.check_openssl.outputs.UPDATE 0"
        fi

    - name: Clone nginx
      id: check_nginx
      run: |
        git clone https://github.com/nginx/nginx.git
        cd nginx
        VER=$(git tag --sort=taggerdate -l 'release-*' | tail -n 1)
        git checkout $VER
        echo "::set-output name=NGINX::$VER"
        echo "[DEBUG] steps.check_nginx.outputs.NGINX" $VER
        current=$(date +%s)
        last=$(git log --pretty=format:"%at" $(git rev-parse HEAD) -1)
        min=`expr $current - $last`
        echo "::set-output name=UPDATE::1"
        if [ $min -gt 86400 ];then
          echo "::set-output name=UPDATE::0"
          echo "[DEBUG] steps.check_nginx.outputs.UPDATE 0"
        fi

    - name: Clone ngx_http_proxy_connect_module
      run: |
        git clone https://github.com/chobits/ngx_http_proxy_connect_module.git

    - name: Compile nginx
      if: ${{ steps.check_nginx.outputs.UPDATE || steps.check_openssl.outputs.UPDATE }}
      run: |
        cur_path=`pwd`
        cd nginx
        mv auto/configure configure
        patch -p1 <../ngx_http_proxy_connect_module/patch/proxy_connect_rewrite_102101.patch
        ./configure  --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-proxy-temp-path=/var/lib/nginx/proxy --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --without-http_memcached_module --without-http_uwsgi_module --without-http_scgi_module --with-http_gzip_static_module --with-http_ssl_module --with-http_stub_status_module --with-http_v2_module --with-openssl="${cur_path}/openssl" --with-openssl-opt=enable-tls1_3 --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-stream_realip_module --add-module="${cur_path}/ngx_http_proxy_connect_module"
        make
        test -d ../nginx_debian/usr/sbin/ || mkdir -p ../nginx_debian/usr/sbin/
        cp objs/nginx ../nginx_debian/usr/sbin/nginx

    - name: Make DEB package
      if: ${{ steps.check_nginx.outputs.UPDATE || steps.check_openssl.outputs.UPDATE }}
      run: |
        pwd
        NG_PKG_SIZE=`du -sk nginx_debian|awk '{print $1}'`
        NG_PKG_VERSION=`cat nginx/src/core/nginx.h |grep "#define NGINX_VERSION" | awk '{print $3}' | sed 's/"//g'`
        test -d "nginx_debian/DEBIAN" || mkdir -p "nginx_debian/DEBIAN" 
        sed -e "s|%%SIZE%%|${NG_PKG_SIZE}|" -e "s|%%VERSION%%|${NG_PKG_VERSION}|" < control_tmpl > nginx_debian/DEBIAN/control
        test -d "nginx_debian/var/lib/nginx" || mkdir -p "nginx_debian/var/lib/nginx"        
        test -d "nginx_debian/var/log/nginx" || mkdir -p "nginx_debian/var/log/nginx"
        test -d "nginx_debian/var/www/html" || mkdir -p "nginx_debian/var/www/html"
        test -d "nginx_debian/etc/nginx/modules-available" || mkdir -p "nginx_debian/etc/nginx/modules-available"
        test -d "nginx_debian/etc/nginx/modules-enabled" || mkdir -p "nginx_debian/etc/nginx/modules-enabled"
        test -d "nginx_debian/etc/nginx/conf.d" || mkdir -p "nginx_debian/etc/nginx/conf.d"
        test -d "nginx_debian/etc/nginx/sites-enabled" || mkdir -p "nginx_debian/etc/nginx/sites-enabled"
        dpkg -b nginx_debian nginx_proxy.deb
    
    - name: Upload artifact
      if: ${{ steps.check_nginx.outputs.UPDATE || steps.check_openssl.outputs.UPDATE }}
      uses: actions/upload-artifact@master
      with:
        name: nginx
        path: |
          nginx_proxy.deb

    - name: Release
      if: ${{ steps.check_nginx.outputs.UPDATE || steps.check_openssl.outputs.UPDATE }}
      uses: djnicholson/release-action@v2.11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-name: ${{ format('v0.{0}', github.run_id) }}
        tag-name: ${{ format('v0.{0}', github.run_id) }}
        asset-name: ${{ format('nginx_proxy_{0}.deb', github.run_id) }}
        file: 'nginx_proxy.deb'
