name: matrix-docker

on:
  push:
    branches:
     - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout project
      uses: actions/checkout@v3
      
    - name: check_release
      id: check_release
      run: |
        chmod +x entrypoint.sh
        echo "FLAG=$(bash check_release.sh)" >> $GITHUB_OUTPUT
        echo "TAG_NAME=$(cat release.version)" >> $GITHUB_OUTPUT

    - name: compile nginx-proxy
      uses: docker://debian:11-slim
      with:
        entrypoint: /github/workspace/entrypoint.sh
        args: 11

    - name: compile nginx-proxy
      uses: docker://debian:12-slim
      with:
        entrypoint: /github/workspace/entrypoint.sh
        args: 12

    - name: upload artifact
      uses: actions/upload-artifact@master
      with:
        name: nginx
        path: |
          nginx_*.deb

    - name: release
      if: ${{ steps.check_release.outputs.FLAG == 1 }}
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ format('nginx_{0}', steps.check_release.outputs.TAG_NAME) }}
        tag: ${{ format('{0}', steps.check_release.outputs.TAG_NAME) }}
        artifacts: '/github/workspace/release/'